spring:
  application:
    name: mutant
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

## PORT
server:
  port: 8080

---

spring:
  profiles: local

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/mutant
    # Username and password
    username: postgres
    password: admin

---

spring:
  profiles: prod

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/mutant
    # Username and password
    username: postgres
    password: admin


