spring:
  application:
    name: mutant

## PORT
server:
  port: 8080

---

spring:
  profiles: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mutant
      user: root
      password: root

---

spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mutant
      user: root
      password: root


