spring:
  application:
    name: mutant
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://database-mutant.cduyj3trapgt.us-east-2.rds.amazonaws.com:5432/mutant
    # Username and password
    username: postgres
    password: mercadolibremutant

## PORT
server:
  port: 8080
